---
- name: Delete WordPress database
  mysql_db: 
    name: {{ wp_db_name }}
    state: absent

- name: Remove all installed packages
  apt: 
    name: "{{ item }}"
    state: absent
  with_items:
    - php-fpm
    - php-common
    - php-mysql
    - nginx
    - mariadb-server
    # - python3-mysqldb

- name: Recursively remove directory
  ansible.builtin.file:
    path: /var/www/wordpress
    state: absent
