---
- name: Install MariaDB package
  ansible.builtin.apt:
    name: mariadb-server
    state: latest

- name: Install "python3-mysqldb" package
  ansible.builtin.apt:
    name: python3-mysqldb
    state: latest

- name: Start MariaDB Service
  service: name=mariadb state=started enabled=yes
  
# If you encounter the "Please explicitly state intended protocol" error,
# use the login_unix_socket argument
- name: Removes anonymous user account for localhost
  community.mysql.mysql_user:
    name: ''
    host: localhost
    state: absent
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Removes all anonymous user accounts
  community.mysql.mysql_user:
    name: ''
    host_all: yes
    state: absent

