---
- name: Install php-fpm and deps
  apt: 
    name: "{{ item }}"
    state: latest
  with_items:
    - php-fpm
    - php-mysql

- name: Start php8.2-fpm
  service: 
    name: php8.2-fpm
    state: started
    enabled: yes