---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
platforms:
  - name: molecule-ubuntu
    #image: ubuntu/python:3.12-24.04_stable
    #image: ubuntu:22.04
    image: python:3.9
provisioner:
  name: ansible
  inventory:
    links:
      # hosts: ../../../inventory/hosts
      group_vars: ../../../../group_vars
      # host_vars: ../../../inventory/host_vars/
  config_options:
    defaults:
      stdout_callback: yaml

verifier:
  name: ansible

scenario:
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy